### ISSUE TITLE
Add WebReflection’s Custom Elements v0 to v1 translation layer polyfill to the workers playground

### ISSUE THREAD

**Issue by ExE-Boss** [cloudflare/templates#10]
WebReflection’s [Custom&nbsp;Elements v0 to&nbsp;v1 translation layer polyfill](https://github.com/WebReflection/ce-v0) translates Custom&nbsp;Elements v0 calls to&nbsp;Custom&nbsp;Elements v1 calls, and with Firefox deciding to&nbsp;not implement Custom&nbsp;Elements v0, only&nbsp;v1, this&nbsp;polyfill is&nbsp;necessary to use the site in&nbsp;Firefox.

The other option would be to rewrite Custom Elements v0 calls to Custom Elements v1 calls.

This will have to be added to the V8 inspector located at https://cloudflareworkers.com/devtools/inspector.html

---

See also https://community.cloudflare.com/t/add-webreflection-s-custom-elements-v0-to-v1-translation-layer-polyfill-to-the-workers-playground/23209

**Comment by lauragift21** [comment]
Thank you @ExE-Boss, for the issue. This is a issue about the playground which, to my knowledge lives in a different location and this templates repo has moved into the workers-sdk monorepo, here:
https://github.com/cloudflare/workers-sdk/tree/main/templates

So I'll be closing out  this issue.
