### ISSUE TITLE
worker-rust build command does not work

### ISSUE THREAD

**Issue by williamdes** [cloudflare/templates#130]
Because ed70362188046632d76fca4aca0a228b7cbba912 changed the README

This is missing in `package.json`
```json
"build": "wrangler build"
```

**Comment by williamdes** [comment]
Also `cfg-if = "1.0.0"` builds locally without any problem so the bump can be commited

**Comment by lauragift21** [comment]
Hello @williamdes! Thanks for creating this issue. The templates have moved to the workers-sdk monorepo, here:
https://github.com/cloudflare/workers-sdk/tree/main/templates

So I'll make a PR to fix this in that repo and close this issue.
