### ISSUE TITLE
Preact Progressive Web App Example

### ISSUE THREAD

**Issue by shalomvolchok** [cloudflare/templates#17]
We just released a demo worker that runs a Preact Progressive Web App in a Cloudflare worker with server side rendering. I don't know if it makes sense to include the whole thing into this repo as an example, but maybe you'd like to link to it?

https://github.com/DigitalOptimizationGroup/cloudflare-worker-preact-pwa

**Comment by lauragift21** [comment]
Hi @shalomvolchok, We're moving the templates over to workers-sdk mono-repo located here:

https://github.com/cloudflare/workers-sdk/tree/main/templates

I know this has been a while, but if you still want to add it to the templates listing, you can send in a PR to get it added to the list of templates.
