### ISSUE TITLE
Combining fast-google-fonts and third-party-scripts?

### ISSUE THREAD

**Issue by ahmed-sigmalux** [cloudflare/templates#19]
Does anyone have a working script that combines the fast-google-fonts and third-party-scripts examples? I've been able to mash them together, but the processing is slightly different in each example and I want to ensure I'm not introducing any fatal errors or bugs, particularly with content-types, charsets, and chunking.

**Comment by ahmed-sigmalux** [comment]
Big thanks, @pmeenan !!!

**Comment by lauragift21** [comment]
Closing this issue as it looks like the original issue was resolved, and the templates no longer live here and have moved to the workers-sdk monorepo located here: https://github.com/cloudflare/workers-sdk/tree/main/templates
