### ISSUE TITLE
TypeScript example

### ISSUE THREAD

**Issue by balupton** [cloudflare/templates#22]
It would be nice for a typescript example of workers. As right now, I can't seem to find any type definitions  for the most basic example:

```
addEventListener('fetch', event => {
  event.respondWith(handleRequest(event.request))
})

/**
 * Fetch and log a given request object
 * @param {Request} request
 */
async function handleRequest(request) {
  console.log('Got request', request)
  const response = await fetch(request)
  console.log('Got response', response)
  return response
}
```

https://github.com/zeit/ncc could probably be used for generating the compiled bundle, as it supports typescript

**Comment by jrf0110** [comment]
For basic examples, you can follow the instructions here https://blog.cloudflare.com/using-webpack-to-bundle-workers/

Cloudflare Workers are a superset of Service Workers, so you can use TypeScript's built-in definitions for webworkers by specifying it in your tsconfig.json:

```javascript
"lib": ["es2015", "webworker"],
```

**Comment by 13rac1** [comment]
I've published complete types and mock: https://github.com/udacity/cloudflare-typescript-workers

**Comment by aequasi** [comment]
would be nice to update that blog post to use babel-loader (the defacto standard for typescript + webpack now), instead of awesome-typescript-loader

**Comment by leoiii12** [comment]
But this is parceljs
https://github.com/leoiii12/cloudflare-workers-forum/tree/master/api/

**Comment by lukeed** [comment]
I know this is old, but this is now available in the [`/worker-typescript`](/worker-typescript) subdirectory. 

You can create a project with it by visiting https://workers.new/typescript or locally via:

```sh
$ npm init cloudflare my-project worker-typescript
# or
$ yarn create cloudflare my-project worker-typescript
# or
$ pnpm create cloudflare my-project worker-typescript
```
