### ISSUE TITLE
Support for third party scripts 

### ISSUE THREAD

**Issue by dschmidtadv** [cloudflare/templates#26]
A lot of scripts nowadays are added to the HTML using code such as 
-----
insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga')
-----
It would be great if caching those locally would be supported.

**Comment by reinder42** [comment]
If I'm not mistaken, JavaScript like that is executed in the browser, so it'll use browser-level caching of the original script (GA, etc.) when possible

**Comment by 350d** [comment]
@dschmidtadv You need to update .js url and point it to your CF proxy folder like `/proxy/www.google-analytics.com/analytics.js` for example.
