### ISSUE TITLE
Edge Cache + CF Argo & hit/miss analytics

### ISSUE THREAD

**Issue by reinder42** [cloudflare/templates#32]
Hi there,

Got a question about the Edge Cache Worker. I hope this is the right spot to ask! If not, let me know :-) Is there any way to keep track of global cache hit/miss statistics? I'd love to know how the edge cache performs.

Thank you!

—Reinder

**Comment by alriksson** [comment]
@reinder42 Argo becomes redundant.

**Comment by lauragift21** [comment]
Hello @reinder42, I hope you got this resolved. You can ask directly on our Discord community if you have any future questions: https://discord.gg/cloudflaredevs

Closing this now as the templates are being moved to the worker-sdk repo located here:
https://github.com/cloudflare/workers-sdk/tree/main/templates
