### ISSUE TITLE
Preload key requests

### ISSUE THREAD

**Issue by wpsumo** [cloudflare/templates#40]
Could we preload <link rel=preload> and prioritize fetching resources such as Google fonts that are optimized. Since the path is changed in the workers upon cache cleared I can not manually add the preload.

@pmeenan https://developers.google.com/web/tools/lighthouse/audits/preload

**Comment by lauragift21** [comment]
Closing this issue because the templates have moved over to the worker-sdk monorepo: https://github.com/cloudflare/workers-sdk/tree/main/templates.

if you're still experiencing issues feel free to open an issue there.
