### ISSUE TITLE
Bypass-all-cookies-except

### ISSUE THREAD

**Issue by fabian-barney** [cloudflare/templates#46]
For some reasons I like to have the inverse logic from the current "bypass-on-cookie" feature.
I do not want to define cookies which bypass but I like to define cookies which are ok for caching.

When a request contains a single cookie that is not on the cookie whitelist then it should bypass the cache. Caching is only allowed when all cookies are on the whitelist.

Main reasons:
- new unknown cookies from plugins etc. 
- security: when updates change the cookie name then protected pages may accidently being cached with the current bypass-on-cookie feature

**Comment by lauragift21** [comment]
Closing this as the main repo has moved over to workers-sdk monorepo, located here: https://github.com/cloudflare/workers-sdk/tree/main/templates. 

Feel free to reopen this issue in that repo if you're still experiencing this issue.
