### ISSUE TITLE
POST /wp-admin/admin-ajax.php 403 (Forbidden)

### ISSUE THREAD

**Issue by willstocks** [cloudflare/templates#50]
Hi guys,
When the Cloudflare Page Cache plugin is enabled on my site, I see 403 errors when trying to hit `/wp-admin/admin-ajax.php` for AJAX functionality (in this case, visit https://willstocks.co.uk and try clicking the little "like"/"thumbs-up" button on each post to like the post)
As soon as I disable the plugin, the error stops and the likes register.
Any ideas?
Thanks,
Will

**Comment by xtuc** [comment]
Do you have a way to see the error generated by the backend?

**Comment by lauragift21** [comment]
This repo has been moved over to the workers-sdk monorepo located here: https://github.com/cloudflare/workers-sdk/tree/main/templates

If you still have further issues around this, feel free to create an issue there. I will be closing this out for now.
