### ISSUE TITLE
Worker routing problem on react app 

### ISSUE THREAD

**Issue by mohamedrajhi** [cloudflare/templates#56]
Hello , 
I have an issue with the routing in my application after deploying it to cloudflare.
The navigation using the navbar works , but if  I copy/paste the same link that works with the navbar navigation i got this error.

Note : in the localhost everything is fine
![image](https://user-images.githubusercontent.com/40335054/85716990-50f59e80-b6ed-11ea-9c2b-85061e5a3fca.png)

**Comment by signalnerve** [comment]
hey @mohamedrajhi, based on the screenshot, it looks like you're using workers sites to deploy your app. for react applications, you should go into your worker (`workers-site/index.js`) and update the code to use the `serveSinglePageApp` function. more docs here:

https://github.com/cloudflare/kv-asset-handler#servesinglepageapp

**Comment by lauragift21** [comment]
Closing as issue was resolved!
