### ISSUE TITLE
--local should not be the default for worker starter templates 

### ISSUE THREAD

**Issue by threepointone** [cloudflare/templates#65]
local mode should not be the default for developing workers, since the behaviour is different from our actual runtime.

**Comment by lauragift21** [comment]
Is this still the case @JacobMGEvans? We are in the process of moving over the templates to workers-sdk monorepo: https://github.com/cloudflare/workers-sdk/tree/main/templates

I'll be closing this for now, and I'll recreate this in the new home for templates if this is still required.
